import "~/styles/globals.css";
import Navbar from "~/components/navbar";
import { ClerkProvider } from "@clerk/nextjs";

export const metadata = {
  title: "Rate My Landlord",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <Navbar />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
